export type Building = {
  id: string;
  code: string;
  name: string;
  area: string;
  kind: string;
  shops: number;
  floors: number;
  goods: number;
  status: "active" | "directory";
  source: string;
};

export const buildings: Building[] = [
  { id: "city-centre-complex", code: "01", name: "City Centre Complex", area: "Kampala CBD", kind: "Commercial Building", shops: 1, floors: 1, goods: 1, status: "active", source: "Kampala City Directory" },
  { id: "nakivubo-trade-centre", code: "01", name: "Nakivubo Trade Centre", area: "Nakivubo", kind: "Commercial Building", shops: 1, floors: 1, goods: 1, status: "active", source: "Kampala City Directory" },
  { id: "mabirizi-complex", code: "01", name: "Mabirizi Complex", area: "Kampala Road", kind: "Commercial Building", shops: 1, floors: 1, goods: 1, status: "active", source: "Kampala City Directory" },
  { id: "nakayiza-market", code: "01", name: "Nakayiza Market", area: "Kisenyi", kind: "Commercial Building", shops: 1, floors: 1, goods: 1, status: "active", source: "Kampala City Directory" },
  { id: "segawa-market", code: "00", name: "Segawa Market", area: "Kisenyi \u00b7 Mwanga II Road", kind: "Market", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala City Directory" },
  { id: "haruna-mall-ntinda", code: "00", name: "Haruna Mall Ntinda", area: "Ntinda", kind: "Mall", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala City Directory" },
  { id: "haruna-towers-wandegeya", code: "00", name: "Haruna Towers Wandegeya", area: "Wandegeya", kind: "Commercial Tower", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala City Directory" },
  { id: "haruna-market-nakivubo", code: "00", name: "Haruna Market Nakivubo", area: "Nakivubo", kind: "Market", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala City Directory" },
  { id: "haruna-towers-nakasero", code: "00", name: "Haruna Towers Nakasero", area: "Nakasero", kind: "Commercial Tower", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala City Directory" },
  { id: "entebbe-new-taxi-park", code: "00", name: "Entebbe New Taxi Park", area: "Clock Tower \u00b7 Entebbe Road", kind: "Transport & Retail Hub", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala City Directory" },
  { id: "senna-arcade", code: "00", name: "Senna Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "haider-arcade", code: "00", name: "Haider Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nagatule-plaza", code: "00", name: "Nagatule Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "grand-corner", code: "00", name: "Grand Corner", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "viena-business-center", code: "00", name: "Viena Business Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "park-enkadde-mall", code: "00", name: "Park Enkadde Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mukwano-mall", code: "00", name: "Mukwano Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "rene-plaza", code: "00", name: "Rene Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "plot-8-arcade-luwum-street", code: "00", name: "Plot 8 Arcade Luwum Street", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "plot-21-luwum-street", code: "00", name: "Plot 21 Luwum Street", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "maria-galleria", code: "00", name: "Maria Galleria", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bunkedeko-arcade", code: "00", name: "Bunkedeko Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "aponye-city-mall", code: "00", name: "Aponye City Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "city-house", code: "00", name: "City House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sarah-mall", code: "00", name: "Sarah Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sal", code: "00", name: "SAL", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "pan-world", code: "00", name: "PAN World", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nkrumah-nasser-link-plaza", code: "00", name: "Nkrumah Nasser Link Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "musana-house", code: "00", name: "Musana House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mukwano-courts", code: "00", name: "Mukwano Courts", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "park-royal", code: "00", name: "Park Royal", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "senana-shopping-center", code: "00", name: "Senana Shopping Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "silver-arcade", code: "00", name: "Silver Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ham-power-point", code: "00", name: "Ham Power Point", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "capital-shoppers-plaza", code: "00", name: "Capital Shoppers Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mm-plaza", code: "00", name: "MM Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ham-towers-and-shopping-mall", code: "00", name: "Ham Towers and Shopping Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "namayiba-building", code: "00", name: "Namayiba Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "namayiba-paaka-plaza", code: "00", name: "Namayiba Paaka Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "king-forward", code: "00", name: "King Forward", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "arua-park-mall", code: "00", name: "Arua Park Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "zaidi-complex", code: "00", name: "Zaidi Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bhatia-tower", code: "00", name: "Bhatia Tower", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "e-tower", code: "00", name: "E Tower", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "em-plaza", code: "00", name: "EM Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "plot-79a", code: "00", name: "Plot 79A", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "youma-building", code: "00", name: "Youma Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "prisma-building", code: "00", name: "Prisma Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "st-paul-books-and-media-center", code: "00", name: "St Paul Books and Media Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "damanico-plaza", code: "00", name: "Damanico Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kalungi-plaza", code: "00", name: "Kalungi Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "biplous-ltd", code: "00", name: "Biplous Ltd", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kati-kati", code: "00", name: "Kati Kati", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "karobwa-towers", code: "00", name: "Karobwa Towers", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "jenna-plaza", code: "00", name: "Jenna Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "namanda-plaza", code: "00", name: "Namanda Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "reco-house", code: "00", name: "Reco House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "cham-tours", code: "00", name: "Cham Tours", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "equatorial-shopping-old", code: "00", name: "Equatorial Shopping Old", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "unia-house", code: "00", name: "Unia House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "numak-house", code: "00", name: "Numak House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "aponye-building", code: "00", name: "Aponye Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kisakyamaliya", code: "00", name: "Kisakyamaliya", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "detail-plaza", code: "00", name: "Detail Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "royal-plaza", code: "00", name: "Royal Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "hanifa-plaza", code: "00", name: "Hanifa Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "electrical-plaza", code: "00", name: "Electrical Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "park-view", code: "00", name: "Park View", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "hardware-plaza", code: "00", name: "Hardware Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "eagle-plaza", code: "00", name: "Eagle Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "market-plaza", code: "00", name: "Market Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nalubega-plaza", code: "00", name: "Nalubega Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "jbk-mall", code: "00", name: "JBK Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nakasule-shopping-center", code: "00", name: "Nakasule Shopping Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "atlanta-textile", code: "00", name: "Atlanta Textile", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "annet-plaza", code: "00", name: "Annet Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "magoba-shopping-arcade", code: "00", name: "Magoba Shopping Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mega-plaza", code: "00", name: "Mega Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "victoria-plaza", code: "00", name: "Victoria Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ham-towers", code: "00", name: "Ham Towers", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mukwano-arcade", code: "00", name: "Mukwano Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mirembe-arcade", code: "00", name: "Mirembe Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "fair-house", code: "00", name: "Fair House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "dembelyo-house", code: "00", name: "Dembelyo House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "copper-complex", code: "00", name: "Copper Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nasser-road-mall", code: "00", name: "Nasser Road Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "miracle-house", code: "00", name: "Miracle House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "universal-house", code: "00", name: "Universal House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "simba-telecom-building", code: "00", name: "Simba Telecom Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "prime-complex", code: "00", name: "Prime Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "rashnaly-ghandi", code: "00", name: "Rashnaly Ghandi", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "blessed-to-bless", code: "00", name: "Blessed to Bless", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "justin-in-case-uganda", code: "00", name: "Justin in Case Uganda", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bhatia-building", code: "00", name: "Bhatia Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nandi-tower", code: "00", name: "Nandi Tower", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ivory-plaza", code: "00", name: "Ivory Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "jesico-plaza", code: "00", name: "Jesico Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "plot-15-rashid-khamis", code: "00", name: "Plot 15 Rashid Khamis", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mukarwe-enterprise-ltd", code: "00", name: "Mukarwe Enterprise Ltd", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "grand-plaza", code: "00", name: "Grand Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "cornerstone-plaza", code: "00", name: "Cornerstone Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "discount-mall", code: "00", name: "Discount Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bulamu-bwebugaga", code: "00", name: "Bulamu Bwebugaga", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kosovo-plaza", code: "00", name: "Kosovo Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kasiwukira-plaza", code: "00", name: "Kasiwukira Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "discover-plaza", code: "00", name: "Discover Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "new-park-mall", code: "00", name: "New Park Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kk-trust-arcade", code: "00", name: "KK Trust Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "lions-shopping-mall", code: "00", name: "Lions Shopping Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "gwanda-shopping-mall", code: "00", name: "Gwanda Shopping Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bunyiri-egg-center", code: "00", name: "Bunyiri Egg Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "rosa-market", code: "00", name: "Rosa Market", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sasa-arcade", code: "00", name: "Sasa Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "apple-towers", code: "00", name: "Apple Towers", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "jumbo-arcade", code: "00", name: "Jumbo Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "victor-arcade", code: "00", name: "Victor Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "premier-arcade", code: "00", name: "Premier Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sunset-plaza", code: "00", name: "Sunset Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "shamba-complex", code: "00", name: "Shamba Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nakivubo-traders-center", code: "00", name: "Nakivubo Traders Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "original-shauriyako-plaza", code: "00", name: "Original Shauriyako Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "best-bargaining-center", code: "00", name: "Best Bargaining Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "angels-plaza", code: "00", name: "Angels Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nana-center", code: "00", name: "Nana Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "pentagon-city-plaza", code: "00", name: "Pentagon City Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "capital-center", code: "00", name: "Capital Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "qualicel-bus-terminal", code: "00", name: "Qualicel Bus Terminal", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "modern-shoplex", code: "00", name: "Modern Shoplex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "master-plaza", code: "00", name: "Master Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ensi-egumire-plaza", code: "00", name: "Ensi Egumire Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sure-house", code: "00", name: "Sure House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "gathani-house", code: "00", name: "Gathani House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "equatorial-shopping-mall-new", code: "00", name: "Equatorial Shopping Mall New", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mabirizi-city-plaza", code: "00", name: "Mabirizi City Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "god-s-grace", code: "00", name: "God's Grace", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "qualicel-house", code: "00", name: "Qualicel House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "amina-william-street", code: "00", name: "Amina William Street", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sky-light", code: "00", name: "Sky Light", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mulima-muyuni-arcade", code: "00", name: "Mulima Muyuni Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nakasero-complex", code: "00", name: "Nakasero Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "katonga-business-center", code: "00", name: "Katonga Business Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "star-shoppers", code: "00", name: "Star Shoppers", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "soweto-arcade", code: "00", name: "Soweto Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "arrow-complex", code: "00", name: "Arrow Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "majestic-plaza", code: "00", name: "Majestic Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "old-park-royal", code: "00", name: "Old Park Royal", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "smile-investments", code: "00", name: "Smile Investments", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "fidodo-building", code: "00", name: "Fidodo Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sembatya-arcade", code: "00", name: "Sembatya Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "boost-house", code: "00", name: "Boost House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "platinum-house", code: "00", name: "Platinum House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "braiden-plaza", code: "00", name: "Braiden Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "edmul-building", code: "00", name: "Edmul Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "gazaland", code: "00", name: "Gazaland", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mutasa-kafeero", code: "00", name: "Mutasa Kafeero", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "downtown-investment", code: "00", name: "Downtown Investment", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "plot-67-kampala-road", code: "00", name: "Plot 67 Kampala Road", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "zam-zam-business-center", code: "00", name: "Zam Zam Business Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "masaka-jubilee-house", code: "00", name: "Masaka Jubilee House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "naiga-chambers", code: "00", name: "Naiga Chambers", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "gagawala-building", code: "00", name: "Gagawala Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "city-complex", code: "00", name: "City Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "galiraya-commercial-plaza", code: "00", name: "Galiraya Commercial Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kirumira-towers", code: "00", name: "Kirumira Towers", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "peacock-building", code: "00", name: "Peacock Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ambassador-house", code: "00", name: "Ambassador House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "energy-center", code: "00", name: "Energy Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kherm-building", code: "00", name: "Kherm Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sayuuni-arcade", code: "00", name: "Sayuuni Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "zebra-house", code: "00", name: "Zebra House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "elite-apartments-meera-investment", code: "00", name: "Elite Apartments Meera Investment", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "jambole-arcade", code: "00", name: "Jambole Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nabukeera-plaza", code: "00", name: "Nabukeera Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sedona-complex", code: "00", name: "Sedona Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "musa-printer-industry", code: "00", name: "Musa Printer Industry", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "titanic-plaza", code: "00", name: "Titanic Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kizito-towers", code: "00", name: "Kizito Towers", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "center-point", code: "00", name: "Center Point", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "zainabu-plaza", code: "00", name: "Zainabu Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sunset-arcade", code: "00", name: "Sunset Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kalmax-building", code: "00", name: "Kalmax Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "corner-house", code: "00", name: "Corner House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "fazil-building", code: "00", name: "Fazil Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "tropical-complex", code: "00", name: "Tropical Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "arua-park-plaza-a", code: "00", name: "Arua Park Plaza A", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "arua-park-plaza-b", code: "00", name: "Arua Park Plaza B", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "giant-shopping-arcade", code: "00", name: "Giant Shopping Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "light-arcade", code: "00", name: "Light Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "justin-arcade", code: "00", name: "Justin Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nabugabo-business-center", code: "00", name: "Nabugabo Business Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "fami-plaza", code: "00", name: "Fami Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "barmako-house", code: "00", name: "Barmako House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "trade-link", code: "00", name: "Trade Link", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "superior-complex", code: "00", name: "Superior Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "transnile-link", code: "00", name: "Transnile Link", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "fortune-plaza", code: "00", name: "Fortune Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "suncity-arcade", code: "00", name: "Suncity Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "moonlight-arcade", code: "00", name: "Moonlight Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "london-building-plot-64-kampala-road", code: "00", name: "London Building Plot 64 Kampala Road", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bonita-arcade", code: "00", name: "Bonita Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "dembe-arcade", code: "00", name: "Dembe Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bypass-building", code: "00", name: "Bypass Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "lutunga-house", code: "00", name: "Lutunga House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ss-plaza", code: "00", name: "SS Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "modern-sarah-center", code: "00", name: "Modern Sarah Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "midcity", code: "00", name: "Midcity", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "manella-white-house", code: "00", name: "Manella White House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kabale-arcade", code: "00", name: "Kabale Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "avemar-shopping-center", code: "00", name: "Avemar Shopping Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "faibah-plaza", code: "00", name: "Faibah Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "zai-plaza", code: "00", name: "Zai Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "namaganda-plaza", code: "00", name: "Namaganda Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "the-arcade", code: "00", name: "The Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "teddy-s-plaza", code: "00", name: "Teddy's Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "jemba-plaza", code: "00", name: "Jemba Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kampala-plaza", code: "00", name: "Kampala Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "zibula-atude", code: "00", name: "Zibula Atude", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sekaziga-house", code: "00", name: "Sekaziga House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nasser-printer-house", code: "00", name: "Nasser Printer House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "printers-miracle-center", code: "00", name: "Printers Miracle Center", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nambusi-arcade", code: "00", name: "Nambusi Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "unifam-plaza", code: "00", name: "Unifam Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "masjid-noor", code: "00", name: "Masjid Noor", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "pacific-arcade", code: "00", name: "Pacific Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "ganith-house", code: "00", name: "Ganith House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "plot-69-kampala-road", code: "00", name: "Plot 69 Kampala Road", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "chicago", code: "00", name: "Chicago", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "zain-textile", code: "00", name: "Zain Textile", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kisenyi-bus-terminal", code: "00", name: "Kisenyi Bus Terminal", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nakivubo-complex", code: "00", name: "Nakivubo Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "printer-arcade", code: "00", name: "Printer Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kob-house", code: "00", name: "KoB House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "emka", code: "00", name: "Emka", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sb-city-plaza", code: "00", name: "SB City Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "echo-plaza", code: "00", name: "Echo Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "sentongo-solomon-plot-33a", code: "00", name: "Sentongo Solomon Plot 33A", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "nampinge-ruth-plot-13a", code: "00", name: "Nampinge Ruth Plot 13A", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "plot-3-johnstone", code: "00", name: "Plot 3 Johnstone", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "executive-house", code: "00", name: "Executive House", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kulusume-bhai", code: "00", name: "Kulusume Bhai", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "star-shine-arcade", code: "00", name: "Star Shine Arcade", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "owino-shopping-mall", code: "00", name: "Owino Shopping Mall", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "bukandula-tower", code: "00", name: "Bukandula Tower", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "royz-plaza", code: "00", name: "RoyZ Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "kapsi-building", code: "00", name: "KAPSI Building", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "hbt-complex", code: "00", name: "HBT Complex", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "mengo-hill-plaza", code: "00", name: "Mengo Hill Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "yamaha-centre", code: "00", name: "Yamaha Centre", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "temusewo-plaza", code: "00", name: "Temusewo Plaza", area: "Kampala CBD", kind: "Commercial Building / Arcade", shops: 0, floors: 0, goods: 0, status: "directory", source: "KCCA CBD Directory" },
  { id: "garden-city-complex", code: "00", name: "Garden City Complex", area: "Greater Kampala", kind: "Shopping Mall", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala Tourism Portal" },
  { id: "oasis-mall", code: "00", name: "Oasis Mall", area: "Greater Kampala", kind: "Shopping Mall", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala Tourism Portal" },
  { id: "lugogo-mall", code: "00", name: "Lugogo Mall", area: "Greater Kampala", kind: "Shopping Mall", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala Tourism Portal" },
  { id: "acacia-mall", code: "00", name: "Acacia Mall", area: "Greater Kampala", kind: "Shopping Mall", shops: 0, floors: 0, goods: 0, status: "directory", source: "Kampala Tourism Portal" },
];

export type Shop = {
  id: string;
  name: string;
  building: string;
  floor: string;
  unit: string;
  category: string;
  goods: number;
};

export const shops: Shop[] = [
  { id: "kampala-fabrics", name: "Kampala Fabrics", building: "City Centre Complex", floor: "Floor 1", unit: "Unit A12", category: "Textiles", goods: 1 },
  { id: "nakivubo-electronics", name: "Nakivubo Electronics", building: "Nakivubo Trade Centre", floor: "Floor 1", unit: "Unit B04", category: "Electronics", goods: 1 },
  { id: "mabirizi-shoes", name: "Mabirizi Shoe Point", building: "Mabirizi Complex", floor: "Floor 1", unit: "Unit C21", category: "Footwear", goods: 1 },
  { id: "nakayiza-produce", name: "Nakayiza Fresh Produce", building: "Nakayiza Market", floor: "Ground", unit: "Stall 07", category: "Food", goods: 1 },
];

export type Good = {
  id: string;
  name: string;
  shop: string;
  building: string;
  price: number;
  unit: string;
};

export const goods: Good[] = [
  { id: "kitenge", name: "Kitenge fabric roll", shop: "Kampala Fabrics", building: "City Centre Complex", price: 45000, unit: "per 6 yards" },
  { id: "phone-charger", name: "Fast phone charger", shop: "Nakivubo Electronics", building: "Nakivubo Trade Centre", price: 25000, unit: "per piece" },
  { id: "leather-sandals", name: "Leather sandals", shop: "Mabirizi Shoe Point", building: "Mabirizi Complex", price: 60000, unit: "per pair" },
  { id: "matooke", name: "Matooke bunch", shop: "Nakayiza Fresh Produce", building: "Nakayiza Market", price: 30000, unit: "per bunch" },
];

export const cityStats = {
  buildings: 253,
  shops: 4,
  goods: 4,
  requests: 0,
  orders: 0,
  chats: 0,
};

export const formatCount = (n: number) => String(n).padStart(3, "0");

export const formatUgx = (n: number) => `UGX ${n.toLocaleString("en-UG")}`;