/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as GoodsRouteImport } from './routes/goods'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as BuildingsIndexRouteImport } from './routes/buildings.index'
import { Route as BuildingsIdRouteImport } from './routes/buildings.$id'
import { Route as ShopsShopIdRouteImport } from './routes/shops_.$shopId'
import { Route as BuildingsIdIndexRouteImport } from './routes/buildings.$id.index'
import { Route as BuildingsIdAddShopRouteImport } from './routes/buildings.$id.add-shop'
import { Route as AuthenticatedShopsShopIdGoodsRouteImport } from './routes/_authenticated/shops.$shopId.goods'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsRoute = GoodsRouteImport.update({
  id: '/goods',
  path: '/goods',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BuildingsIndexRoute = BuildingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildingsRoute,
} as any)
const BuildingsIdRoute = BuildingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuildingsRoute,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops_/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsIdIndexRoute = BuildingsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildingsIdRoute,
} as any)
const BuildingsIdAddShopRoute = BuildingsIdAddShopRouteImport.update({
  id: '/add-shop',
  path: '/add-shop',
  getParentRoute: () => BuildingsIdRoute,
} as any)
const AuthenticatedShopsShopIdGoodsRoute =
  AuthenticatedShopsShopIdGoodsRouteImport.update({
    id: '/shops/$shopId/goods',
    path: '/shops/$shopId/goods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buildings': typeof BuildingsRouteWithChildren
  '/goods': typeof GoodsRoute
  '/orders': typeof OrdersRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shops': typeof ShopsRoute
  '/splash': typeof SplashRoute
  '/account': typeof AuthenticatedAccountRoute
  '/buildings/$id': typeof BuildingsIdRouteWithChildren
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/buildings/$id/add-shop': typeof BuildingsIdAddShopRoute
  '/buildings/$id/': typeof BuildingsIdIndexRoute
  '/shops/$shopId/goods': typeof AuthenticatedShopsShopIdGoodsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/goods': typeof GoodsRoute
  '/orders': typeof OrdersRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shops': typeof ShopsRoute
  '/splash': typeof SplashRoute
  '/account': typeof AuthenticatedAccountRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/buildings': typeof BuildingsIndexRoute
  '/buildings/$id/add-shop': typeof BuildingsIdAddShopRoute
  '/buildings/$id': typeof BuildingsIdIndexRoute
  '/shops/$shopId/goods': typeof AuthenticatedShopsShopIdGoodsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buildings': typeof BuildingsRouteWithChildren
  '/goods': typeof GoodsRoute
  '/orders': typeof OrdersRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shops': typeof ShopsRoute
  '/splash': typeof SplashRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/buildings/$id': typeof BuildingsIdRouteWithChildren
  '/shops_/$shopId': typeof ShopsShopIdRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/buildings/$id/add-shop': typeof BuildingsIdAddShopRoute
  '/buildings/$id/': typeof BuildingsIdIndexRoute
  '/_authenticated/shops/$shopId/goods': typeof AuthenticatedShopsShopIdGoodsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buildings'
    | '/goods'
    | '/orders'
    | '/requests'
    | '/reset-password'
    | '/shops'
    | '/splash'
    | '/account'
    | '/buildings/$id'
    | '/shops/$shopId'
    | '/buildings/'
    | '/buildings/$id/add-shop'
    | '/buildings/$id/'
    | '/shops/$shopId/goods'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/goods'
    | '/orders'
    | '/requests'
    | '/reset-password'
    | '/shops'
    | '/splash'
    | '/account'
    | '/shops/$shopId'
    | '/buildings'
    | '/buildings/$id/add-shop'
    | '/buildings/$id'
    | '/shops/$shopId/goods'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buildings'
    | '/goods'
    | '/orders'
    | '/requests'
    | '/reset-password'
    | '/shops'
    | '/splash'
    | '/_authenticated/account'
    | '/buildings/$id'
    | '/shops_/$shopId'
    | '/buildings/'
    | '/buildings/$id/add-shop'
    | '/buildings/$id/'
    | '/_authenticated/shops/$shopId/goods'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuildingsRoute: typeof BuildingsRouteWithChildren
  GoodsRoute: typeof GoodsRoute
  OrdersRoute: typeof OrdersRoute
  RequestsRoute: typeof RequestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopsRoute: typeof ShopsRoute
  SplashRoute: typeof SplashRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods': {
      id: '/goods'
      path: '/goods'
      fullPath: '/goods'
      preLoaderRoute: typeof GoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/buildings/': {
      id: '/buildings/'
      path: '/'
      fullPath: '/buildings/'
      preLoaderRoute: typeof BuildingsIndexRouteImport
      parentRoute: typeof BuildingsRoute
    }
    '/buildings/$id': {
      id: '/buildings/$id'
      path: '/$id'
      fullPath: '/buildings/$id'
      preLoaderRoute: typeof BuildingsIdRouteImport
      parentRoute: typeof BuildingsRoute
    }
    '/shops_/$shopId': {
      id: '/shops_/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/$id/': {
      id: '/buildings/$id/'
      path: '/'
      fullPath: '/buildings/$id/'
      preLoaderRoute: typeof BuildingsIdIndexRouteImport
      parentRoute: typeof BuildingsIdRoute
    }
    '/buildings/$id/add-shop': {
      id: '/buildings/$id/add-shop'
      path: '/add-shop'
      fullPath: '/buildings/$id/add-shop'
      preLoaderRoute: typeof BuildingsIdAddShopRouteImport
      parentRoute: typeof BuildingsIdRoute
    }
    '/_authenticated/shops/$shopId/goods': {
      id: '/_authenticated/shops/$shopId/goods'
      path: '/shops/$shopId/goods'
      fullPath: '/shops/$shopId/goods'
      preLoaderRoute: typeof AuthenticatedShopsShopIdGoodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedShopsShopIdGoodsRoute: typeof AuthenticatedShopsShopIdGoodsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedShopsShopIdGoodsRoute: AuthenticatedShopsShopIdGoodsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BuildingsIdRouteChildren {
  BuildingsIdAddShopRoute: typeof BuildingsIdAddShopRoute
  BuildingsIdIndexRoute: typeof BuildingsIdIndexRoute
}

const BuildingsIdRouteChildren: BuildingsIdRouteChildren = {
  BuildingsIdAddShopRoute: BuildingsIdAddShopRoute,
  BuildingsIdIndexRoute: BuildingsIdIndexRoute,
}

const BuildingsIdRouteWithChildren = BuildingsIdRoute._addFileChildren(
  BuildingsIdRouteChildren,
)

interface BuildingsRouteChildren {
  BuildingsIdRoute: typeof BuildingsIdRouteWithChildren
  BuildingsIndexRoute: typeof BuildingsIndexRoute
}

const BuildingsRouteChildren: BuildingsRouteChildren = {
  BuildingsIdRoute: BuildingsIdRouteWithChildren,
  BuildingsIndexRoute: BuildingsIndexRoute,
}

const BuildingsRouteWithChildren = BuildingsRoute._addFileChildren(
  BuildingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuildingsRoute: BuildingsRouteWithChildren,
  GoodsRoute: GoodsRoute,
  OrdersRoute: OrdersRoute,
  RequestsRoute: RequestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopsRoute: ShopsRoute,
  SplashRoute: SplashRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
